collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Post" # Used in the UI
    folder: "src/pages/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Layout", name: "layout", widget: "text", default: "../../layouts/MarkdownPostLayout.astro" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "author", name: "Author", widget: "string" }
      - { label: "pubDate", name: "date", widget: "datetime" }
      - { label: "description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media

backend:
  name: github
  repo: paxtonm342/paxtonm342.github.io
  branch: main
  base_url: https://sveltia-cms-auth.flowerfoxdev.workers.dev/
  

  