collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Post" # Used in the UI
    folder: "src/pages/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Layout", name: "layout", widget: "string", default: "../../layouts/MarkdownPostLayout.astro" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "pubDate", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

media_libraries:
  default:
    config:
      transformations:
        raster_image: # original format
          format: webp # new format, only `webp` is supported
          quality: 85 # default: 85
          width: 2048 # default: original size
          height: 2048 # default: original size
        svg:
          optimize: true

media_folder: "src/images" # Location where files will be stored in the repo
public_folder: "src/images" # The src attribute for uploaded media

backend:
  name: github
  repo: paxtonm342/paxtonm342.github.io
  branch: main
  base_url: https://sveltia-cms-auth.flowerfoxdev.workers.dev/
  

  